SWP\Component\Bridge\Model\Package:
    exclusion_policy: ALL
    properties:
        items:
            expose: true
            serialized_name: associations
            type: ArrayCollection<string,SWP\Component\Bridge\Model\Item>
            groups: [deserialization]
        body:
            expose: true
            serialized_name: body_html
            type: string
            groups: [api]
        createdAt:
            expose: true
            type: DateTime
            groups: [api]
        updatedAt:
            expose: true
            type: DateTime
            groups: [api]
        groups:
            expose: true
            serialized_name: extra_items
            type: ArrayCollection<string,SWP\Component\Bridge\Model\Group>
            groups: [deserialization]

    virtual_properties:
        getItemsArray:
            serialized_name: associations
            type: array
            groups: [api]
        getGroupsArray:
            serialized_name: extra_items
            type: array
            groups: [api]
