SWP\Component\Bridge\Model\Group:
    exclusion_policy: ALL
    properties:
        code:
            expose: true
            type: string
            serialized_name: id
            groups: [api, api_groups_list]
        type:
            expose: true
            type: string
            groups: [api, api_groups_list]
        items:
            expose: true
            type: ArrayCollection<SWP\Component\Bridge\Model\Item>
            groups: [api]
