SWP\Component\Bridge\Model\Rendition:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups: [api]
        href:
            expose: true
            type: string
            groups: [api]
        width:
            expose: true
            type: integer
            groups: [api]
        height:
            expose: true
            type: integer
            groups: [api]
        mimetype:
            expose: true
            type: string
            groups: [api]
        media:
            expose: true
            type: string
            groups: [api]
        name:
            expose: true
            type: string
            groups: [api]
